name: Release
on:
  push:
    tags:
      - '*'
jobs:
  automate:
    runs-on: ubuntu-18.04
    env:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NOTIFICATION_URL: ${{ secrets.RELEASE_NOTIFICATION_URL }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: yarn
      - run: grunt release --skip-tests
      - uses: jogindersingh1985/action-ghost-release@main
